//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class Course_Student
    {
        public int Course_StudentID { get; set; }
        public int CourseID { get; set; }
        public int StudentID { get; set; }
    
        public virtual Courses Courses { get; set; }
        public virtual Student Student { get; set; }
    }
}
