//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class Courses
    {
        public int CourseID { get; set; }
        public string Name { get; set; }
        public string Section { get; set; }
        public int Credits { get; set; }
        public int CareerID { get; set; }
        public int TeacherID { get; set; }
        public string Schedule { get; set; }
    
        public virtual Career Career { get; set; }
        public virtual Teacher Teacher { get; set; }
        public virtual CourseStudent CourseStudent { get; set; }
    }
}
