//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class CourseStudent
    {
        public int CourseStudentID { get; set; }
        public int CSCourseID { get; set; }
        public int CSStudentID { get; set; }
    
        public virtual Courses Courses { get; set; }
        public virtual Student Student { get; set; }
    }
}
